extern long double atanl(long double);
extern long double cosl (long double);
extern long double sinl(long double);
extern long double tanl(long double);
extern long double tanhl(long double);
extern long double frexpl(long double, int *);
extern long double modfl(long double, long double *);
extern long double ceill(long double);
extern long double fabsl(long double); 
extern long double floorl(long double);
extern long double log1pl(long double);
extern long double expm1l(long double);
extern long double acosl(long double);
extern long double asinl(long double);
extern long double atan2l(long double, long double);
extern long double coshl(long double);
extern long double sinhl(long double);
extern long double expl(long double);
extern long double ldexpl(long double, int);
extern long double logl(long double);
extern long double log10l(long double);
extern long double powl(long double, long double);
extern long double fmodl(long double, long double);
extern long double copysignl(long double, long double);
extern long double nanl(const char *);
extern int ilogbl(long double);
extern long double asinhl(long double);
extern long double cbrtl(long double);
extern long double nextafterl(long double, long double);
extern float nexttowardf(float, long double);
extern double nexttoward(double, long double);
extern long double nexttowardl(long double, long double);
extern long double logbl(long double);
extern long double log2l(long double);
extern long double rintl(long double);
extern long double scalbnl(long double, int);
extern long double exp2l(long double);
extern long double scalblnl(long double, long);
extern long double tgammal(long double);
extern long double nearbyintl(long double);
extern long int lrintl(long double);
extern long long int llrintl(long double);
extern long double roundl(long double);
extern long lroundl(long double);
extern long long int llroundl(long double);
extern long double truncl(long double);
extern long double remquol(long double, long double, int *);
extern long double fdiml(long double, long double);
extern long double fmaxl(long double, long double);
extern long double fminl(long double, long double);
extern long double fmal(long double, long double, long double);
extern long double acoshl(long double);
extern long double atanhl(long double);
extern long double remainderl(long double, long double);
extern long double lgammal(long double);
extern long double erfl(long double);
extern long double erfcl(long double);

#include_next <math.h>
